name: champion_maung
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2

  flutter_staggered_animations: ^1.1.1
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  dropdown_button2: ^2.3.9
  omni_datetime_picker: ^2.0.2
  data_table_2: ^2.5.12
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Fonts
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/TimesNewRoman-Bold.ttf
        - asset: assets/fonts/TimesNewRoman-Bold.ttf
          weight: 500

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/login_background.png
    - images/logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
